import type { IngredientCategory, IngredientId } from './ai.types';
import type { DietaryRestriction, FitnessGoal } from './profile.types';
import type { MealType } from '../features/nutrition/utils/meal-suggestions';

export type RecipeMealType = MealType;
export type RecipeDifficulty = 'easy' | 'medium';

/** Display units for recipe ingredient quantities. */
export type IngredientQuantityUnit =
  | 'g'
  | 'ml'
  | 'piece'
  | 'tbsp'
  | 'tsp'
  | 'slice'
  | 'cup'
  | 'pinch';

export interface RecipeIngredientQuantity {
  amount: number;
  unit: IngredientQuantityUnit;
}

/** Coarse tags used for badges on recipe cards. */
export type RecipeTag =
  | 'high_protein'
  | 'quick'
  | 'low_calorie'
  | 'mass_gain'
  | 'recomposition'
  | 'vegetarian'
  | 'budget'
  | 'no_cook';

export type RecipeSource = 'internal' | 'ai';

/**
 * Internal recipe — fully deterministic, with i18n keys for every text the
 * UI may display. The nutritional fields are intentionally labeled as
 * **estimates** ("~520 kcal") in the UI: they are sane averages, not
 * medically-validated values.
 */
export interface InternalRecipe {
  id: string;
  source: 'internal';
  mealType: MealType;
  /** i18n key resolved against the `common` namespace. */
  titleKey: string;
  /** i18n key for the short copy under the title. */
  descriptionKey: string;
  /** Internal catalog ids the recipe primarily relies on. */
  ingredientIds: IngredientId[];
  /** Optional ingredients — counted as bonus matches but never penalising. */
  optionalIngredientIds?: IngredientId[];
  /**
   * Approximate quantities per ingredient (required + optional). The UI
   * renders them through i18n unit keys, so they translate to "50 g" /
   * "1 piece" / "1 c. à soupe" depending on the active language. The
   * amounts are rough averages — not medically validated.
   */
  ingredientQuantities?: Partial<
    Record<IngredientId, RecipeIngredientQuantity>
  >;
  /**
   * Categories of *unmapped* fridge items the recipe can also use (e.g.
   * generic spices, condiments). Only used to slightly bias the score when
   * the user has confirmed unmapped items in those categories.
   */
  allowedUnmappedIngredientCategories?: IngredientCategory[];
  /**
   * Hard exclusion list — even if the user has all the required ingredients,
   * the recipe is skipped when ANY of these ids are confirmed (e.g. a
   * "no-onion" variant might forbid onions).
   */
  forbiddenIngredientIds?: IngredientId[];
  prepTimeMinutes: number;
  difficulty: RecipeDifficulty;
  estimatedCalories: number;
  estimatedProteinG: number;
  estimatedCarbsG: number;
  estimatedFatG: number;
  /** Ordered list of i18n keys for the cooking steps. */
  stepKeys: string[];
  tags: RecipeTag[];
  /** Goals the recipe is a good fit for. */
  compatibleGoals: FitnessGoal[];
  /**
   * Restrictions the recipe IS compatible with. A recipe with no entries
   * here is treated as restriction-agnostic (compatible with everything).
   */
  dietaryRestrictionsCompatibility: DietaryRestriction[];
}

/**
 * AI-generated recipe — same surface as the internal one but with raw
 * strings instead of i18n keys (the AI generates content directly in the
 * user's language). Has its own discreet "Proposée par IA" badge.
 */
export interface AIGeneratedRecipe {
  id: string;
  source: 'ai';
  mealType: MealType;
  title: string;
  description: string;
  /** Free-text ingredient labels (mapped + unmapped, generated by the AI). */
  ingredientLabels: string[];
  prepTimeMinutes: number;
  difficulty: RecipeDifficulty;
  estimatedCalories: number;
  estimatedProteinG: number;
  estimatedCarbsG: number;
  estimatedFatG: number;
  steps: string[];
  tags: RecipeTag[];
}

export type Recipe = InternalRecipe | AIGeneratedRecipe;

/**
 * Result of scoring a recipe against the user's confirmed fridge. The match
 * arrays drive the "ingredients you already have / missing" sections of the
 * recipe card.
 */
export interface RecipeMatch {
  recipe: Recipe;
  /** Higher = better match. Combines ingredient overlap, goal fit, and tags. */
  score: number;
  matchedIngredientIds: IngredientId[];
  missingIngredientIds: IngredientId[];
  optionalIngredientIds: IngredientId[];
  /** i18n keys explaining *why* the recipe is a good match — UI displays as chips. */
  matchReasonKeys: string[];
  /**
   * True when the recipe matches a notable share of the fridge — used to
   * surface the "Bon match frigo" badge.
   */
  goodFridgeMatch: boolean;
}

/** Snapshot of a recipe the user has chosen for a given mealType + day. */
export interface ChosenRecipeSnapshot {
  /** Stable id of the recipe, namespaced by source: "internal:..." / "ai:...". */
  recipeId: string;
  source: RecipeSource;
  mealType: MealType;
  title: string;
  description: string;
  estimatedCalories: number;
  estimatedProteinG: number;
  estimatedCarbsG: number;
  estimatedFatG: number;
  prepTimeMinutes: number;
  tags: RecipeTag[];
  /** ISO timestamp the user confirmed the choice. */
  chosenAt: string;
}
